baseURL = "https://c1i.net/"
languageCode = "ja"
title = "イーインのドラマデータ"
theme = "LoveIt"
canonifyURLs = true
relativeURLs = false
enableRobotsTXT = true
enableGitInfo   = true
defaultContentLanguage = "ja"
timeZone = "Asia/Tokyo"

[params]
  title = "イーインのドラマメモ"
  description = "中国のファンタジー時代劇ドラマのデータ"
  images = ["/images/ogp-default.jpg"]
  defaultThumbnail = "/images/default-ogp.jpg"
  defaultTheme = "auto"
  showCodeCopyButtons = true
  dateFormat = "2006-01-02"
  showReadingTime = true
  showLastMod = true
  enableHeadAddons = true

[params.assets]
  customCSS = ["css/custom.css"]

[[menu.main]]
  identifier = "home"
  name = "ホーム"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "data"
  name = "データ"
  url = "/data/"
  weight = 2

[[menu.main]]
  name = "プライバシー"
  url = "/privacy-policy/"
  weight = 50

[[menu.main]]
  name = "お問い合わせ"
  url = "/contact/"
  weight = 60

[[menu.main]]
  name = "運営者情報"
  url = "/about/"
  weight = 70

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML"]

[params.footer]
copyright = "© 2025 藝瑩(YiYing)"

[params.author]
name = "藝瑩(YiYing)"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  category = "categories"
  tag = "tags"


